"use client";

import type { CSSProperties } from "react";
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  BadgeCheck,
  Banknote,
  Bell,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarX,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CircleHelp,
  CircleSlash,
  CircleX,
  Clock,
  Coins,
  CreditCard,
  Dot,
  Download,
  EllipsisVertical,
  ExternalLink,
  FileDown,
  FileText,
  Globe,
  Heart,
  Hourglass,
  Info,
  KeyRound,
  Languages,
  Layers,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Minus,
  MonitorSmartphone,
  Moon,
  Navigation,
  Package,
  PackageCheck,
  PackageOpen,
  Phone,
  Play,
  Plus,
  ReceiptText,
  RefreshCw,
  Repeat,
  Search,
  SearchX,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Sun,
  Trash2,
  TreePalm,
  TriangleAlert,
  Truck,
  User,
  UserX,
  Wallet,
  WifiOff,
  X,
  Zap,
} from "lucide-react";

// Kebab-name → component. Statically imported so icons render on the server
// (no lazy/Suspense) and tree-shake to only what's referenced here.
//
// An unmapped name falls back to `Dot`, which is silent — so every name passed
// anywhere in `src/components/shop` and `src/app/[locale]/shop` belongs here.
// A batch of them did not, which is why the shop's warning notices were drawing
// a small dot where a triangle was meant to be.
const ICONS: Record<string, LucideIcon> = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-down": ArrowUpDown,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  bell: Bell,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "calendar-x": CalendarX,
  check: Check,
  "check-check": CheckCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-alert": CircleAlert,
  "circle-check-big": CircleCheckBig,
  "circle-help": CircleHelp,
  "circle-slash": CircleSlash,
  "circle-x": CircleX,
  clock: Clock,
  coins: Coins,
  "credit-card": CreditCard,
  dot: Dot,
  download: Download,
  "ellipsis-vertical": EllipsisVertical,
  "external-link": ExternalLink,
  "file-down": FileDown,
  "file-text": FileText,
  globe: Globe,
  heart: Heart,
  hourglass: Hourglass,
  info: Info,
  "key-round": KeyRound,
  languages: Languages,
  layers: Layers,
  "layout-grid": LayoutGrid,
  list: List,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  minus: Minus,
  "monitor-smartphone": MonitorSmartphone,
  moon: Moon,
  navigation: Navigation,
  package: Package,
  "package-check": PackageCheck,
  "package-open": PackageOpen,
  // `Palmtree` is lucide's deprecated alias for this glyph; the current export
  // is `TreePalm`, and the shop's holiday notice asks for the old name.
  palmtree: TreePalm,
  phone: Phone,
  play: Play,
  plus: Plus,
  "receipt-text": ReceiptText,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  search: Search,
  "search-x": SearchX,
  settings: Settings,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sun: Sun,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  truck: Truck,
  user: User,
  "user-x": UserX,
  wallet: Wallet,
  "wifi-off": WifiOff,
  x: X,
  zap: Zap,
};

export interface IconProps {
  name: string;
  size?: number;
  strokeWidth?: number;
  color?: string;
  className?: string;
  style?: CSSProperties;
}

/** Renders a lucide icon by the design's kebab-case name. */
export function Icon({ name, size = 20, strokeWidth = 2, color, className, style }: IconProps) {
  const Cmp = ICONS[name] ?? Dot;
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      color={color}
      className={className}
      style={style}
    />
  );
}
