/**
 * Mock catalog data for the Shop — ported from the Claude Design bundle
 * (WiMallDesignSystem_cc21b6). Shapes mirror the backend; images use the
 * design's Picsum placeholder seeds. Swap this module for real API calls later.
 */
import { slugify } from "./format";
import type { Product, ProductType, SortKey, Vendor } from "./shop.types";

const img = (seed: string, n = 1): string[] =>
  Array.from({ length: n }, (_, i) => `https://picsum.photos/seed/${seed}-${i}/700/700`);

const banner = (seed: string): string => `https://picsum.photos/seed/${seed}/1200/500`;

export const vendors: Vendor[] = [
  {
    id: "bella",
    slug: "maison-bella",
    name: "Maison Bella",
    city: "Douala",
    country: "Cameroon",
    products: 48,
    verified: true,
    isOpen: true,
    banner: banner("bella-banner"),
    desc: "Contemporary African fashion, handmade in Douala. Wax prints, accessories & made-to-order pieces.",
    agency: "WiExpress",
    whatsapp: "+237 6 70 00 00 00",
    rating: 4.8,
    reviews: 320,
  },
  {
    id: "souk",
    slug: "tech-souk",
    name: "Tech Souk",
    city: "Yaoundé",
    country: "Cameroon",
    products: 62,
    verified: true,
    isOpen: true,
    banner: banner("souk-banner"),
    desc: "Digital courses, e-books and software for African creators and developers.",
    agency: null,
    whatsapp: "+237 6 99 00 00 00",
    rating: 4.7,
    reviews: 210,
  },
  {
    id: "bela",
    slug: "bela-beaute",
    name: "Bela Beauté",
    city: "Douala",
    country: "Cameroon",
    products: 12,
    verified: false,
    isOpen: true,
    banner: banner("bela-banner"),
    desc: "Mobile beauty & grooming — book a stylist to your door.",
    agency: null,
    whatsapp: "+237 6 55 00 00 00",
    rating: 4.9,
    reviews: 96,
  },
  {
    id: "kmer",
    slug: "kmer-craft",
    name: "Kmer Craft",
    city: "Bafoussam",
    country: "Cameroon",
    products: 27,
    verified: false,
    isOpen: false,
    banner: banner("kmer-banner"),
    desc: "Handwoven raffia, beadwork and home décor from the West region.",
    agency: "GrandNord Logistics",
    whatsapp: "+237 6 77 00 00 00",
    rating: 4.4,
    reviews: 52,
  },
];

// Raw products (slug is derived from the title below).
const rawProducts: Omit<Product, "slug">[] = [
  {
    id: "p1",
    vendorId: "bella",
    type: "physical",
    category: "Fashion",
    title: "Ankara wax print maxi dress",
    rating: 4.6,
    reviews: 214,
    sales: 512,
    images: img("wimall-dress", 4),
    delivery: "Free delivery",
    inStock: true,
    options: [
      { name: "Size", values: ["S", "M", "L", "XL"] },
      { name: "Color", values: ["Indigo", "Coral", "Emerald"] },
    ],
    variants: [
      { id: "v1", name: "M / Indigo", price: 9900, compareAt: 12500, stock: 8, sku: "DRESS-IND-M" },
      { id: "v2", name: "L / Coral", price: 10500, compareAt: 12500, stock: 3, sku: "DRESS-COR-L" },
    ],
    price: 9900,
    compareAt: 12500,
    desc: "Comfortable, breathable cotton wax print. True to size, hand-finished in Douala. Ships within 2 business days.",
  },
  {
    id: "p2",
    vendorId: "kmer",
    type: "physical",
    category: "Home",
    title: "Handwoven raffia tote bag",
    rating: 4.4,
    reviews: 52,
    sales: 130,
    images: img("wimall-bag", 3),
    delivery: "Delivery available",
    inStock: true,
    options: [{ name: "Color", values: ["Natural", "Black"] }],
    variants: [{ id: "v3", name: "Natural", price: 7500, stock: 20, sku: "TOTE-NAT" }],
    price: 7500,
    desc: "Durable handwoven raffia with leather handles. Each piece is unique.",
  },
  {
    id: "p3",
    vendorId: "bella",
    type: "physical",
    category: "Fashion",
    title: "Beaded statement necklace",
    rating: 4.7,
    reviews: 88,
    sales: 240,
    images: img("wimall-neck", 3),
    delivery: "Free delivery",
    inStock: false,
    options: [],
    variants: [{ id: "v4", name: "One size", price: 4500, stock: 0, sku: "NECK-01" }],
    price: 4500,
    desc: "Hand-strung glass beads on a durable cord.",
  },
  {
    id: "p4",
    vendorId: "souk",
    type: "digital",
    category: "Courses",
    title: "Complete React & TypeScript course — 42 hours",
    rating: 4.9,
    reviews: 88,
    sales: 1200,
    images: img("wimall-course", 2),
    inStock: true,
    digital: { license: "Single user", access: "Lifetime", downloads: 5, platforms: "Web, iOS, Android" },
    options: [{ name: "Format", values: ["Video + PDF", "PDF only"] }],
    variants: [
      { id: "v5", name: "Video + PDF", price: 15000, stock: 0, sku: "REACT-FULL", format: "ZIP · 4.2 GB" },
      { id: "v6", name: "PDF only", price: 6000, stock: 0, sku: "REACT-PDF", format: "PDF · 32 MB" },
    ],
    price: 6000,
    compareAt: null,
    desc: "From fundamentals to production apps. 42 hours of video, source code, and a 320-page PDF companion.",
  },
  {
    id: "p5",
    vendorId: "souk",
    type: "digital",
    category: "E-books",
    title: "Startup finance playbook (e-book)",
    rating: 4.5,
    reviews: 34,
    sales: 300,
    images: img("wimall-ebook", 1),
    inStock: true,
    digital: { license: "Single user", access: "1 year", downloads: 3, platforms: "PDF, EPUB" },
    options: [{ name: "Format", values: ["PDF", "EPUB"] }],
    variants: [{ id: "v7", name: "PDF", price: 3500, stock: 0, sku: "FIN-PDF", format: "PDF · 8 MB" }],
    price: 3500,
    desc: "A practical guide to managing cash, pricing and fundraising for African startups.",
  },
  {
    id: "p6",
    vendorId: "bela",
    type: "service",
    category: "Beauty",
    title: "Home haircut & styling session",
    rating: 4.8,
    reviews: 31,
    sales: 90,
    images: img("wimall-salon", 3),
    inStock: true,
    service: { duration: 60, mode: "calendar", location: "At your address (Douala)", buffer: 15 },
    options: [],
    variants: [{ id: "v8", name: "Booking", price: 5000, stock: 0, sku: "HAIRCUT-60" }],
    price: 5000,
    desc: "A professional stylist comes to you. Cut, wash and style — 60 minutes. Price is per session.",
  },
  {
    id: "p7",
    vendorId: "bella",
    type: "physical",
    category: "Fashion",
    title: "Kente-trim linen shirt",
    rating: 4.3,
    reviews: 40,
    sales: 75,
    images: img("wimall-shirt", 3),
    delivery: "Free delivery",
    inStock: true,
    options: [{ name: "Size", values: ["M", "L", "XL"] }],
    variants: [{ id: "v9", name: "L", price: 8500, stock: 12, sku: "SHIRT-L" }],
    price: 8500,
    desc: "Breathable linen with a hand-stitched kente trim.",
  },
  {
    id: "p8",
    vendorId: "kmer",
    type: "physical",
    category: "Home",
    title: "Carved wooden serving bowl set",
    rating: 4.6,
    reviews: 22,
    sales: 60,
    images: img("wimall-bowl", 2),
    delivery: "Delivery available",
    inStock: true,
    options: [],
    variants: [{ id: "v10", name: "Set of 3", price: 11000, stock: 6, sku: "BOWL-3" }],
    price: 11000,
    desc: "Hand-carved from a single piece of sustainable hardwood.",
  },
];

export const products: Product[] = rawProducts.map((p) => ({ ...p, slug: slugify(p.title) }));

export const categories: string[] = ["All", "Fashion", "Home", "Courses", "E-books", "Beauty"];

export const sorts: SortKey[] = [
  "Relevance",
  "Popularity",
  "Newest",
  "Price: low to high",
  "Price: high to low",
];

export const productTypes: ProductType[] = ["physical", "digital", "service"];
